version: 1.0.{build}
os: Visual Studio 2015

environment:
    COVERALLS_REPO_TOKEN:  
       secure: D3xk3zhufhpC3ZTVEFQT4jGsSmEWWzNJdJsAUu2wK2EARb9Z3LO4Uaubq7HM007j

install:
    - nuget restore
  
build:
  project: Sloth.sln
  verbosity: minimal

after_build:
  7z a slothpad.zip %APPVEYOR_BUILD_FOLDER%\SlothPad\bin\Debug\*
  
artifacts:
  - path: slothpad.zip
    name: SlothPad